name: Deploy Microservices

on:
  push:
    branches: [ "main" ]

jobs:
  build-usuario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven (usuario)
        run: mvn -B package --file usuario/pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "mateus1711"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push usuario image
        uses: docker/build-push-action@v5
        with:
          context: ./usuario
          file: ./usuario/Dockerfile
          push: true
          tags: mateus1711/usuario-ci:${{ github.sha }}
      - name: Deploy usuario via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: "ubuntu"
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            docker stop usuario || true
            docker rm --force usuario || true
            docker run -d -p 8080:8080 --name usuario --network=rede mateus1711/usuario-ci:${{ github.sha }}

  build-loja:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven (loja)
        run: mvn -B package --file loja/pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "mateus1711"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push loja image
        uses: docker/build-push-action@v5
        with:
          context: ./loja
          file: ./loja/Dockerfile
          push: true
          tags: mateus1711/loja-ci:${{ github.sha }}
      - name: Deploy loja via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: "ubuntu"
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            docker stop loja || true
            docker rm --force loja || true
            docker run -d -p 8081:8081 --name loja --network=rede mateus1711/loja-ci:${{ github.sha }}

  build-produto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven (produto)
        run: mvn -B package --file produto/pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "mateus1711"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push produto image
        uses: docker/build-push-action@v5
        with:
          context: ./produto
          file: ./produto/Dockerfile
          push: true
          tags: mateus1711/produto-ci:${{ github.sha }}
      - name: Deploy produto via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: "ubuntu"
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            docker stop produto || true
            docker rm --force produto || true
            docker run -d -p 8082:8082 --name produto --network=rede mateus1711/produto-ci:${{ github.sha }}
