name: Deploy Loja

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (loja)
      run: mvn -B package --file loja/pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "mateus1711"
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push loja image
      uses: docker/build-push-action@v5
      with:
        context: ./loja
        file: ./loja/Dockerfile
        push: true
        tags: mateus1711/loja-ci:${{ github.sha }}

    - name: Deploy loja via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }}
        username: "ubuntu"
        key: ${{ secrets.KEY_TEST }}
        port: 22
        script: |
          docker stop loja || true
          docker rm --force loja || true
          docker run -d -p 8081:8081 --name loja --network=rede mateus1711/loja-ci:${{ github.sha }}
